Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: main
      CodeUri: C:\Users\670282139\GolandProjects\getBooksApi\getOneBook
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: books